### ISSUE TITLE
Graphical corruption in 320x200 modes

### ISSUE THREAD

**Issue by classilla** [urxp/drally#10]
This might be specific to `ppc64le` (or my system, or video card - WX7100 under Fedora 35), but the 320x200 modes have graphical corruption on the top and bottom borders. Uncommenting these lines helps, though it doesn't eliminate it completely. Not sure why they were commented originally.

```
diff --git a/drally_linux_c.c b/drally_linux_c.c
index 7d86759..c0d7a48 100644
--- a/drally_linux_c.c
+++ b/drally_linux_c.c
@@ -230,19 +230,19 @@ void __VGA3_SETMODE(void){
        GX.ActiveMode = VGA3;
 }
 
 void __VGA13_SETMODE(void){
 
        if(GX.ActiveMode != VGA13){
 
                GX.Surface = GX.VGA13.Surface;
-       //      SDL_SetRenderDrawColor(GX.Renderer, 0, 0, 0, 255);
-       //      SDL_RenderClear(GX.Renderer);
-       //      SDL_RenderPresent(GX.Renderer);
+               SDL_SetRenderDrawColor(GX.Renderer, 0, 0, 0, 255);
+               SDL_RenderClear(GX.Renderer);
+               SDL_RenderPresent(GX.Renderer);
                SDL_RenderSetLogicalSize(GX.Renderer, 320, 200);
                if(SDL_GetWindowFlags(GX.Window)&SDL_WINDOW_HIDDEN) SDL_ShowWindow(GX.Window);
                GX.ActiveMode = VGA13;
        }
 }
 
 void __VESA101_SETMODE(void){
 
```

Otherwise, the game plays great. There's a segfault if you let the demo run too long, but it's not something most people will hit, and I'll file that separately. Thanks for this, I loved this game back in the day, and it's more convenient to play it native than in DOSBox.

**Comment by urxp** [comment]
Hi, thank you for trying my little project. I'm aware of this issue. The content of 640x480 mode flickers at the top and bottom part of the screen. The problem is it sometimes does and sometimes it doesn't no matter if those lines are commented or not. I don't know how to reproduce it. Only part solution i could think of was creating the full 320x240 buffer with black stripes but i didn't like this idea.

**Comment by classilla** [comment]
Hmm. I'll keep messing with it. It seems to be worst in the video playback - I don't notice it much during gameplay, so maybe that's a clue.

**Comment by classilla** [comment]
Playing it in DOSBox, it shifts back and forth between the 320x200 aspect ratio and the 640x480 aspect ratio. How do you feel about a patch to do that? It should get around the problem.

**Comment by classilla** [comment]
(by which I mean it actually shrinks the window)

**Comment by urxp** [comment]
I gave it a try https://github.com/urxp/dRally/commit/a6fb2f018803c9ab4c1214fb82f21016318368bd with the explicit compile option -DDR_LETTERBOX to preserve letterbox mode. As far as i can remember the transition between different window sizes felt "physically unpleasant" to my eyes.

**Comment by classilla** [comment]
Just played it through (nailed the Adversary in one go!). Looks great. Thanks!
