### ISSUE TITLE
how do you obtain the asembly code?

### ISSUE THREAD

**Issue by enriquesomolinos** [urxp/drally#3]
hi,
i'm doing a project similar to yours with death rally. Great job!!

i have one question about how you ojtain this assbly code, what tools help you to obtain this code from the exe?

thanks and continue with this amazing job

**Comment by urxp** [comment]
hello,

the original exe uses pmode/w extender which encrypts the file into its own PMW1 format and makes it impossible to disassemble the file using software like IDA or Ghidra.

Fortunatelly i found an unofficial tool called PMWUNLIT which decrypts PMW1 into pure LE format (guess i have also used a tool called PMWBIND). I think IDA can read this format. Even so i wrote my own disassembler for LE (death rally specific) called bin2inc . It is a complete mess but it does the job.

I know about your project and i am checking your progress from time to time. I know it is pretty tedious job.
