### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cyberbeat** [urxp/drally#9]
Game crashes after about 30 seconds in race:

gdb ./drally_linux 
GNU gdb (GDB; openSUSE Tumbleweed) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./drally_linux...
(gdb) run
Starting program: dRally/drally_linux 
Missing separate debuginfos, use: zypper install glibc-32bit-debuginfo-2.33-1.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Death Rally *** Full Version 1.1
[New Thread 0xe484eac0 (LWP 28555)]
[dRally.SOUND] Opening audio device.
[New Thread 0xd46ffac0 (LWP 28556)]
[dRally.SOUND] Audio opened: 22050 hz, 2 channels, 512 samples

Loading music & effects, please wait...
[dRally.SOUND] MSX: MEN-MUS.CMF, SFX: MEN-SAM.CMF
[dRally.Memory] Memory lock failed!
============= S3M resize: 505857 >>>>  53840
=============  XM resize: 323793 >>>>    639
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Clean] ___12200h
[dRally.Clean] ___12a54h
[dRally.Clean] ___24ec0h
[dRally.Clean] ___2fc50h
[dRally.SOUND] MSX: TR5-MUS.CMF, SFX: GEN-EFE.CMF
[dRally.Memory] Memory lock failed!
============= S3M resize: 325036 >>>>  32048
=============  XM resize: 385187 >>>>   1800
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!
[dRally.Memory] Memory lock failed!

Thread 1 "drally_linux" received signal SIGSEGV, Segmentation fault.
0x080ae53f in race___50ef4h () at race___50ef4h.c:104
104                                                                     if(B(edx) != 0) B(esi+D(esp)+eax+D(esp+0x28)+0x5c) = B(edx);
Missing separate debuginfos, use: zypper install libFLAC8-32bit-debuginfo-1.3.3-1.5.x86_64 libSDL2-2_0-0-32bit-debuginfo-2.0.14-1.1.x86_64 libX11-6-32bit-debuginfo-1.7.0-1.1.x86_64 libXau6-32bit-debuginfo-1.0.9-1.7.x86_64 libXcursor1-32bit-debuginfo-1.2.0-1.5.x86_64 libXext6-32bit-debuginfo-1.3.4-1.7.x86_64 libXi6-32bit-debuginfo-1.7.10-1.5.x86_64 libXinerama1-32bit-debuginfo-1.1.4-1.8.x86_64 libXrandr2-32bit-debuginfo-1.5.2-1.7.x86_64 libXrender1-32bit-debuginfo-0.9.10-1.12.x86_64 libXxf86vm1-32bit-debuginfo-1.1.4-1.17.x86_64 libasound2-32bit-debuginfo-1.2.4-3.1.x86_64 libgcrypt20-32bit-debuginfo-1.8.7-1.1.x86_64 libglvnd-32bit-debuginfo-1.3.2-2.1.x86_64 libgpg-error0-32bit-debuginfo-1.41-1.1.x86_64 liblz4-1-32bit-debuginfo-1.9.3-1.1.x86_64 libpulse0-32bit-debuginfo-14.2-1.1.x86_64 libsndfile1-32bit-debuginfo-1.0.28-10.5.x86_64 libspeex1-32bit-debuginfo-1.2-1.12.x86_64 libsystemd0-32bit-debuginfo-246.9-1.1.x86_64 libvorbis0-32bit-debuginfo-1.3.7-1.2.x86_64 libvorbisenc2-32bit-debuginfo-1.3.7-1.2.x86_64 libxcb1-32bit-debuginfo-1.14-1.3.x86_64 libzstd1-32bit-debuginfo-1.4.8-2.1.x86_64

(gdb) bt
#0  0x080ae53f in race___50ef4h () at race___50ef4h.c:104
#1  0x08087c7e in race_main (A1=0, A2=4) at race_main.c:1285
#2  0x0805896e in ___33010h_cdecl (A1=4) at ___33010h.c:1083
#3  0x080615df in ___3266ch () at ___3266ch.c:443
#4  0x080d7554 in shop_main () at shop_main.c:241
#5  0x080d38f5 in menu___194a8h () at menu___194a8h.c:89
#6  0x080d2802 in menu_main () at menu_main.c:239
#7  0x0804e778 in ___3e720h () at ___3e720h.c:58
#8  0x080495c7 in main (argc=1, argv=0xffffce74) at drally.c:41

**Comment by cyberbeat** [comment]
Thanks, works now! Is it possible to enable fullscreen mode?

**Comment by urxp** [comment]
This feature is not implemented. There is only 4:3 windowed mode at this moment.

**Comment by cyberbeat** [comment]
Oh, that would be a great feature, to get parity with the dosbox-version
